### ISSUE TITLE
Support loading .nc4 extensioned netCDF-4 files

### ISSUE THREAD

**Issue by mathomp4** [silx-kit/vscode-h5web#10]
### Is your feature request related to a problem?

As discussed on the HDF Forum here:

https://forum.hdfgroup.org/t/vscode-extension-for-hdf5/9769

I recently tried to open a netCDF4 file with the extension by renaming the file from `test.nc4` to `test.h5`. The first time I tried that, it didn't work and I thought this would be a bug issue. But today I tried it and it did work! 

I then looked around your repo and found https://github.com/silx-kit/vscode-h5web/pull/4 and found that if I rename the file `test.nc` your extension will open that is well. 

So at this point, it's all down to the fact my code and group output `.nc4` files.

### Requested solution or feature

Support opening `.nc4` like you do `.nc` for netCDF4 files, please. 

### Alternatives you've considered

Well, I could rename the files to `.nc` but, well, I'm lazy. 😄 

I did check if your extension had settings where I could enable extra file extensions, but I didn't see that.

### Additional context

Since you asked in the nice issue template, here is what I see for a `.nc4` file:

<img width="1200" alt="Screen Shot 2022-07-21 at 3 37 22 PM" src="https://user-images.githubusercontent.com/2982494/180301034-2fa5e839-1685-4519-980f-7a7ff9732012.png">

but if I rename as `.nc`:

<img width="1200" alt="Screen Shot 2022-07-21 at 3 37 58 PM" src="https://user-images.githubusercontent.com/2982494/180301133-238ebbaf-840a-49c1-aa74-9e975fb99fe5.png">

Your extension is cool!

**Comment by axelboc** [comment]
Haha thanks! Glad your file is working after all; maybe you were opening it from outside of your workspace folder (e.g. with drag-and-drop), which it turns out wasn't possible until we fixed in [v0.0.2](https://github.com/silx-kit/vscode-h5web/releases/)? :shrug: 

Anyway, I'll add the `nc4` extension now, no worries :wink: 

FYI, @mkitti [pointed us](https://github.com/silx-kit/vscode-h5web/pull/7#issuecomment-1191250271) to the VS Code setting `workbench.editorAssociations` to set up custom associations. I'm adding it to the README in: https://github.com/silx-kit/vscode-h5web/pull/9 (will merge now).

**Comment by mathomp4** [comment]
@axelboc Just wanted to say that I can confirm it works! Thanks.
